/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {colors:{"secondary-container":"#97f5cc","on-secondary-container":"#007353","on-primary-fixed":"#00164e","surface-dim":"#d2d9f4","background":"#faf8ff","inverse-surface":"#283044","inverse-primary":"#b6c4ff","tertiary":"#d4af37","on-error-container":"#93000a","surface-container-highest":"#dae2fd","secondary-fixed-dim":"#7bd8b1","inverse-on-surface":"#eef0ff","error-container":"#ffdad6","tertiary-fixed":"#fef0c7","surface-container-low":"#f2f3ff","surface-container":"#eaedff","outline":"#757682","primary":"#00236f","surface-container-high":"#e2e7ff","on-error":"#ffffff","on-tertiary-container":"#7a5900","on-surface-variant":"#444651","on-primary":"#ffffff","on-tertiary-fixed-variant":"#664d00","outline-variant":"#c5c5d3","on-secondary":"#ffffff","on-secondary-fixed":"#002115","primary-fixed-dim":"#b6c4ff","on-surface":"#131b2e","surface-variant":"#dae2fd","tertiary-fixed-dim":"#fce38a","surface-container-lowest":"#ffffff","on-primary-fixed-variant":"#264191","error":"#ba1a1a","on-tertiary-fixed":"#4a3600","surface":"#faf8ff","secondary":"#006c4e","on-primary-container":"#90a8ff","on-tertiary":"#ffffff","surface-tint":"#4059aa","primary-container":"#1e3a8a","tertiary-container":"#fef0c7","surface-bright":"#faf8ff","on-secondary-fixed-variant":"#00513a","primary-fixed":"#dce1ff","on-background":"#131b2e","secondary-fixed":"#97f5cc"},borderRadius:{"DEFAULT":"0.25rem","lg":"0.5rem","xl":"0.75rem","full":"9999px"},spacing:{"space-lg":"1.5rem","gutter":"1.5rem","space-xs":"0.25rem","gutter-mobile":"1rem","space-md":"1rem","margin-mobile":"1rem","margin":"2rem","space-sm":"0.5rem","space-xl":"2.5rem"},fontFamily:{"label-md":["Inter"],"body-lg":["Inter"],"label-sm":["Inter"],"body-md":["Inter"],"headline-lg-mobile":["Plus Jakarta Sans"],"headline-md":["Plus Jakarta Sans"],"display-lg":["Plus Jakarta Sans"],"display-lg-mobile":["Plus Jakarta Sans"],"label-lg":["Inter"],"metric-lg":["Plus Jakarta Sans"],"headline-sm":["Plus Jakarta Sans"],"headline-lg":["Plus Jakarta Sans"],"body-sm":["Inter"]},fontSize:{"label-md":["12px",{lineHeight:"16px",letterSpacing:"0.02em",fontWeight:"500"}],"body-lg":["16px",{lineHeight:"24px",fontWeight:"400"}],"label-sm":["11px",{lineHeight:"14px",letterSpacing:"0.04em",fontWeight:"600"}],"body-md":["14px",{lineHeight:"20px",fontWeight:"400"}],"headline-lg-mobile":["22px",{lineHeight:"28px",fontWeight:"600"}],"headline-md":["20px",{lineHeight:"28px",letterSpacing:"-0.01em",fontWeight:"600"}],"display-lg":["36px",{lineHeight:"44px",letterSpacing:"-0.02em",fontWeight:"700"}],"display-lg-mobile":["28px",{lineHeight:"36px",letterSpacing:"-0.01em",fontWeight:"700"}],"label-lg":["14px",{lineHeight:"20px",fontWeight:"600"}],"metric-lg":["30px",{lineHeight:"36px",letterSpacing:"-0.02em",fontWeight:"700"}],"headline-sm":["16px",{lineHeight:"24px",fontWeight:"600"}],"headline-lg":["28px",{lineHeight:"36px",letterSpacing:"-0.02em",fontWeight:"700"}],"body-sm":["12px",{lineHeight:"16px",fontWeight:"400"}]}
    }
  },
  plugins: [],
}
