/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed": "#e5e2e1",
              "on-surface-variant": "#534344",
              "tertiary": "#191919",
              "surface-container": "#efeee9",
              "surface-container-highest": "#e3e3de",
              "ink-black": "#070707",
              "surface-container-high": "#e9e8e3",
              "on-secondary": "#ffffff",
              "outline-variant": "#d8c1c3",
              "background": "#faf9f4",
              "on-tertiary-fixed": "#1c1b1b",
              "academic-gold": "#D3BC7C",
              "on-primary-container": "#d37b89",
              "secondary-fixed-dim": "#dcc584",
              "on-surface": "#1b1c19",
              "surface-container-lowest": "#ffffff",
              "outline": "#867274",
              "inverse-primary": "#ffb2bd",
              "on-error": "#ffffff",
              "on-secondary-container": "#75632c",
              "surface-dim": "#dbdad5",
              "on-error-container": "#93000a",
              "on-primary": "#ffffff",
              "tertiary-fixed-dim": "#c9c6c5",
              "surface-variant": "#e3e3de",
              "on-primary-fixed": "#3d0414",
              "primary": "#390111",
              "surface-bright": "#faf9f4",
              "on-tertiary-fixed-variant": "#474646",
              "primary-fixed-dim": "#ffb2bd",
              "error": "#ba1a1a",
              "heritage-burgundy": "#551625",
              "on-primary-fixed-variant": "#762f3e",
              "inverse-on-surface": "#f2f1ec",
              "on-tertiary-container": "#969494",
              "on-background": "#1b1c19",
              "on-tertiary": "#ffffff",
              "tertiary-container": "#2e2d2d",
              "primary-fixed": "#ffd9dd",
              "error-container": "#ffdad6",
              "surface-tint": "#934655",
              "primary-container": "#551625",
              "secondary-fixed": "#f9e19d",
              "inverse-surface": "#30312e",
              "on-secondary-fixed-variant": "#554511",
              "secondary-container": "#f9e19d",
              "paper-white": "#F9F8F3",
              "surface-container-low": "#f5f4ef",
              "surface": "#faf9f4",
              "secondary": "#6e5d27",
              "on-secondary-fixed": "#231a00"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "container-max": "1280px",
              "margin-desktop": "48px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "unit": "8px"
      },
      "fontFamily": {
              "display-lg-mobile": ["Playfair Display"],
              "body-lg": ["Inter"],
              "headline-md": ["Playfair Display"],
              "body-md": ["Inter"],
              "display-lg": ["Playfair Display"],
              "headline-lg": ["Playfair Display"],
              "label-md": ["Inter"],
              "headline-sm": ["Playfair Display"],
              "body-sm": ["Inter"],
              "headline-lg-mobile": ["Playfair Display"],
              "label-lg": ["Inter"]
      },
      "fontSize": {
              "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg": ["40px", {"lineHeight": "48px", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
