/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed": "#e1e2e5",
              "on-surface-variant": "#434353",
              "tertiary": "#191919",
              "surface-container": "#e9e9ef",
              "surface-container-highest": "#dedee3",
              "ink-black": "#070707",
              "surface-container-high": "#e3e3e9",
              "on-secondary": "#ffffff",
              "outline-variant": "#c1c1d8",
              "background": "#f4f4fa",
              "on-tertiary-fixed": "#1c1b1b",
              "academic-gold": "#a4a4d0",
              "on-primary-container": "#343494",
              "secondary-fixed-dim": "#a4a4d0",
              "on-surface": "#1b1c19",
              "surface-container-lowest": "#ffffff",
              "outline": "#727286",
              "inverse-primary": "#dbdbfa",
              "on-error": "#ffffff",
              "on-secondary-container": "#3c3c8c",
              "surface-dim": "#d5d5db",
              "on-error-container": "#93000a",
              "on-primary": "#ffffff",
              "tertiary-fixed-dim": "#c5c6c9",
              "surface-variant": "#dedee3",
              "on-primary-fixed": "#04043d",
              "primary": "#343494",
              "surface-bright": "#f4f4fa",
              "on-tertiary-fixed-variant": "#474646",
              "primary-fixed-dim": "#dbdbfa",
              "error": "#ba1a1a",
              "heritage-burgundy": "#3c3c94",
              "on-primary-fixed-variant": "#343494",
              "inverse-on-surface": "#ececf2",
              "on-tertiary-container": "#969494",
              "on-background": "#1b1c19",
              "on-tertiary": "#ffffff",
              "tertiary-container": "#2e2d2d",
              "primary-fixed": "#dbdbfa",
              "error-container": "#ffdad6",
              "surface-tint": "#464693",
              "primary-container": "#3c3c94",
              "secondary-fixed": "#dbdbfa",
              "inverse-surface": "#30312e",
              "on-secondary-fixed-variant": "#111155",
              "secondary-container": "#dbdbfa",
              "paper-white": "#f3f3f9",
              "surface-container-low": "#eff0f5",
              "surface": "#f4f4fa",
              "secondary": "#5454a4",
              "on-secondary-fixed": "#000023"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "container-max": "1280px",
              "margin-desktop": "48px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "unit": "8px"
      },
      "fontFamily": {
              "display-lg-mobile": ["Playfair Display"],
              "body-lg": ["Inter"],
              "headline-md": ["Playfair Display"],
              "body-md": ["Inter"],
              "display-lg": ["Playfair Display"],
              "headline-lg": ["Playfair Display"],
              "label-md": ["Inter"],
              "headline-sm": ["Playfair Display"],
              "body-sm": ["Inter"],
              "headline-lg-mobile": ["Playfair Display"],
              "label-lg": ["Inter"]
      },
      "fontSize": {
              "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg": ["40px", {"lineHeight": "48px", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
