/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const AcademicProgramsLazyRouteImport = createFileRoute('/academic-programs')()
const AdmissionsLazyRouteImport = createFileRoute('/admissions')()
const CampusGalleryLazyRouteImport = createFileRoute('/campus-gallery')()
const ContactUsLazyRouteImport = createFileRoute('/contact-us')()
const LeadershipBoardLazyRouteImport = createFileRoute('/leadership-board')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AcademicProgramsLazyRoute = AcademicProgramsLazyRouteImport.update({
  id: '/academic-programs',
  path: '/academic-programs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/academic-programs.lazy').then((d) => d.Route),
)
const AdmissionsLazyRoute = AdmissionsLazyRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admissions.lazy').then((d) => d.Route))
const CampusGalleryLazyRoute = CampusGalleryLazyRouteImport.update({
  id: '/campus-gallery',
  path: '/campus-gallery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/campus-gallery.lazy').then((d) => d.Route),
)
const ContactUsLazyRoute = ContactUsLazyRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact-us.lazy').then((d) => d.Route))
const LeadershipBoardLazyRoute = LeadershipBoardLazyRouteImport.update({
  id: '/leadership-board',
  path: '/leadership-board',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/leadership-board.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/academic-programs': typeof AcademicProgramsLazyRoute
  '/admissions': typeof AdmissionsLazyRoute
  '/campus-gallery': typeof CampusGalleryLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/leadership-board': typeof LeadershipBoardLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/academic-programs': typeof AcademicProgramsLazyRoute
  '/admissions': typeof AdmissionsLazyRoute
  '/campus-gallery': typeof CampusGalleryLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/leadership-board': typeof LeadershipBoardLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/academic-programs': typeof AcademicProgramsLazyRoute
  '/admissions': typeof AdmissionsLazyRoute
  '/campus-gallery': typeof CampusGalleryLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/leadership-board': typeof LeadershipBoardLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-programs'
    | '/admissions'
    | '/campus-gallery'
    | '/contact-us'
    | '/leadership-board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-programs'
    | '/admissions'
    | '/campus-gallery'
    | '/contact-us'
    | '/leadership-board'
  id:
    | '__root__'
    | '/'
    | '/academic-programs'
    | '/admissions'
    | '/campus-gallery'
    | '/contact-us'
    | '/leadership-board'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AcademicProgramsLazyRoute: typeof AcademicProgramsLazyRoute
  AdmissionsLazyRoute: typeof AdmissionsLazyRoute
  CampusGalleryLazyRoute: typeof CampusGalleryLazyRoute
  ContactUsLazyRoute: typeof ContactUsLazyRoute
  LeadershipBoardLazyRoute: typeof LeadershipBoardLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-programs': {
      id: '/academic-programs'
      path: '/academic-programs'
      fullPath: '/academic-programs'
      preLoaderRoute: typeof AcademicProgramsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-gallery': {
      id: '/campus-gallery'
      path: '/campus-gallery'
      fullPath: '/campus-gallery'
      preLoaderRoute: typeof CampusGalleryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-board': {
      id: '/leadership-board'
      path: '/leadership-board'
      fullPath: '/leadership-board'
      preLoaderRoute: typeof LeadershipBoardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AcademicProgramsLazyRoute: AcademicProgramsLazyRoute,
  AdmissionsLazyRoute: AdmissionsLazyRoute,
  CampusGalleryLazyRoute: CampusGalleryLazyRoute,
  ContactUsLazyRoute: ContactUsLazyRoute,
  LeadershipBoardLazyRoute: LeadershipBoardLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
